[workspace]
resolver = "2"

members = [
    "culsynth",
    "culsynth_plugin",
    "culsynth_bindings",
    "culsynth_2040",
]

default-members = [ "culsynth_plugin" ]

[workspace.package]
edition = "2021"
repository = "https://github.com/rbmj/culsynth"
version = "0.2.0"
authors = ["R Blair Mason"]
license = "MIT"

[profile.dev]
opt-level = 1
