[package]
name = "culsynth"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Culsynth DSP Library"

[lib]
name = "culsynth"
path = "src/lib.rs"
crate_type = ["rlib"]

[dependencies]
fixed = "1.24"
num-traits = { version = "0.2", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
arrayvec = { version = "0.7.4", default-features = false }

[features]
libm = ["num-traits/libm"]
rand_defaults = ["rand/default"]

