[package]
name = "culsynth_plugin"
description = "Culsynth Software Synthesizer"
version.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true


[lib]
name = "culsynth_plugin"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[[bin]]
name = "culsynth-standalone"
path = "src/main.rs"

[dependencies]
nih_plug = { git = "https://github.com/rbmj/nih-plug.git", version = "0.0.0", features = ["standalone", "vst3"] }
nih_plug_egui = { git = "https://github.com/rbmj/nih-plug.git", version = "0.0.0" }
fixed = "1.24"
lazy_static = "1.4.0"
regex = "1.10.3"
piano_keyboard = "0.2.3"
rand = { workspace = true }
wmidi = {workspace = true }

culsynth = { path = "../culsynth", version = "0.2.0", features = ["rand_defaults"]}
