[package]
name = "culsynth_plugin"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Culsynth Software Synthesizer"

[lib]
name = "culsynth_plugin"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[[bin]]
name = "culsynth-standalone"
path = "src/main.rs"

[dependencies]
nih_plug = { git = "https://github.com/rbmj/nih-plug.git", features = ["standalone", "vst3"] }
nih_plug_egui = { git = "https://github.com/rbmj/nih-plug.git" }
atomic_float = "0.1"
fixed = "1.24"
piano_keyboard = "0.2.3"
rand = "0.8"

culsynth = { path = "../culsynth", features = ["rand_defaults"]}
