name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libasound2-dev libgl-dev libjack-dev libx11-xcb-dev  libxcb1-dev libxcb-dri2-0-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: wasm32-unknown-unknown
    - name: Install wasm-toolchain
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-bindgen,wasm-pack
    - name: Build
      run: cargo build --verbose
    - name: Cache files
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests for library
      run: cargo test --verbose -p culsynth
    - name: Run tests for plugin
      run: cargo test --verbose

    - name: Build webapp audioworklet
      run: wasm-pack build --target web --no-typescript --out-dir ../static/pkg culsynth_plugin --no-default-features --features "audioworklet"
    - name: build webapp editorui
      run: wasm-pack build --target web --no-typescript --out-dir ../static/pkg culsynth_web
    - name: Upload to GitHub Pages
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: static/
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
